### ISSUE TITLE
Using 'watchers' gives stars instead

### ISSUE THREAD

**Issue by teodosii** [benjycui/react-github-button#9]
Hey,

First of all, thank you for the plugin. Great to see github-buttons implemented for react.

I've tried using `watchers` on my own repo and it gives number of stars instead, so using this
```jsx
<GitHubButton type="watchers" namespace="teodosii" repo="react-notifications-component" />
```

gives `390` stars instead of `4` watchers.

Also in your samples, instead of showing `2` for watchers, it shows `29`.

**Comment by benjycui** [comment]
It is GitHub's bug, see https://api.github.com/repos/benjycui/react-github-button
